version: 2

project_name: jira8

builds:
  - main: .
    binary: jira8
    ldflags:
      - -s -w
      - -X github.com/amplia/jira8/cmd.version={{.Version}}
      - -X github.com/amplia/jira8/cmd.commit={{.ShortCommit}}
      - -X github.com/amplia/jira8/cmd.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))?\!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))?\!?:.+$'
      order: 1
    - title: Other
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^test:"
